version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/mom"
    schedule:
      interval: "monthly"
    allow:
      - dependency-name: "*"
        dependency-type: "direct:production"
        update-types: ["version-update:semver-patch", "security-advisory"]