@startuml Generators class diagram
title Generators class diagram

package Generators {
    class MazeFactory {
        + static createMaze(): Maze
        + static createMaze(int: width, int: height, int:width): Maze
        + static generateRooms(): Tile[]
    }

    class MonsterFactory {
        + createZombie()
        + createGhost()
        + createBoss()
    }

    class PotionFactory {
        + createHealthPotion()
        + createStrenghPotion()
        + createSpeedPotion()
    }

    class WeaponFactory {
        + createSword()
        + createBow()
        + createAxe()
    }

    class MonsterSpawner {
        + spawnMonsters(maze: Maze): Maze
    }

    class ItemSpawner {
        + spawnItems(maze: Maze): Maze
    }

    package tree {
        class Leaf {
            int x
            int y
            int height
            int width
            Leaf left
            Leaf right
            + Leaf(int: x, int: y, int: width, int: height)
            + split(): boolean
            + createRooms()
            + createHalls(Rectangle l, Rectangle r)
            + exportToArray(Tile[] maze, int mazeHeight, int mazeWidth, int mazeDepth)
            + getRoom(): Rectangle
            + getLeft(): Leaf
            + getRight(): Leaf
            + getHeight(): int
            + getWidth(): int
            + randomInt(intmin, int max): int
        }
        class Rectangle {
            int x
            int y
            int width
            int height
            int bottom
            int top
            int left
            int right
            + Rectangle(int: x, int: y, int: width, int: height)
            + populateMazeWithRectangle(Tile[], int mazeHeight, int mazeWidth, int mazeDepth)
            + getX(): int
            + getY(): int
            + getWidth(): int
            + getHeight(): int       
            + getTop(): int
            + getBottom(): int          
            + getLeft(): int
            + getRight(): int
        }
        class Point {
            int x
            int y
            + Point(int x, int y)
            + getX(): int
            + getY(): int
        }

        Leaf -- "*" Rectangle
    }
}

@enduml