@startuml game-loop.png
title Main game loop

participant "w: Window" as window
participant "e: EventManager" as events
participant "s: Scene" as scene
participant "t: Time" as time

activate window
    window -> events : getEvents()
    activate events
        window <-- events: events
    deactivate events
    
    window -> time: update()
    activate time
        window <-- time
    deactivate time

    loop events
        window -> scene: onEvent(event)
        activate scene
            window <-- scene
        deactivate scene
    end

    window -> scene: update()
    activate scene
        scene -> time: getDeltaTime()
        activate time
            scene <-- time: deltaTime
        deactivate time
        window <-- scene
    deactivate scene

    window -> scene: render()
    activate scene
        scene -> time: getDeltaTime()
        activate time
            scene <-- time: deltaTime
        deactivate time
        window <-- scene
    deactivate scene

@enduml