@startuml Attack sequence diagram
title Attack sequence diagram

actor "User" as user
participant "p: Player" as player
participant "w: Weapon" as weapon
participant "m: Monster" as monster

user -> player : attack(m)
activate player
    player -> player : isInFOV(p, m)
    player -> weapon: attack(m)
    activate weapon
        weapon -> weapon: distance = getDistance(m)
        alt distance <= range
            weapon -> monster: takeDamage(damage)
            activate monster
                weapon <-- monster
            deactivate monster
            player <-- weapon: true
        end
        player <-- weapon: false
    deactivate weapon
    user <-- player
deactivate player

@enduml